-- User Performance Views

-- Total Invoices Created by Each User
CREATE OR REPLACE VIEW V_USER_TOTAL_INVOICES AS
SELECT
    u.USER_ID,
    u.USERNAME,
    COUNT(i.INVOICE_ID) AS TOTAL_INVOICES
FROM users u
LEFT JOIN invoices i ON u.USER_ID = i.USER_ID
GROUP BY u.USER_ID, u.USERNAME;

select * from v_user_total_invoices;


-- Total Sales Revenue per each User
CREATE OR REPLACE VIEW V_USER_TOTAL_REVENUE AS
SELECT
    u.USER_ID,
    u.USERNAME,
    SUM(d.QUANTITY * d.UNIT_PRICE - NVL(d.DISCOUNT,0)) AS TOTAL_REVENUE
FROM users u
LEFT JOIN invoices i ON u.USER_ID = i.USER_ID
LEFT JOIN invoices_details d ON i.INVOICE_ID = d.INVOICE_ID
GROUP BY u.USER_ID, u.USERNAME;

-- Total items sold by Each User
CREATE OR REPLACE VIEW V_USER_TOTAL_ITEMS_SOLD AS
SELECT
    u.USER_ID,
    u.USERNAME,
    SUM(d.QUANTITY) AS TOTAL_ITEMS_SOLD
FROM users u
LEFT JOIN invoices i ON u.USER_ID = i.USER_ID
LEFT JOIN invoices_details d ON i.INVOICE_ID = d.INVOICE_ID
GROUP BY u.USER_ID, u.USERNAME;

-- Total Customers served per each User
CREATE OR REPLACE VIEW V_USER_TOTAL_CUSTOMERS AS
SELECT
    u.USER_ID,
    u.USERNAME,
    COUNT(DISTINCT i.CUSTOMER_ID) AS TOTAL_CUSTOMERS_SERVED
FROM users u
LEFT JOIN invoices i ON u.USER_ID = i.USER_ID
GROUP BY u.USER_ID, u.USERNAME;


-- Total Discounts Given by each User
CREATE OR REPLACE VIEW V_USER_TOTAL_DISCOUNTS AS
SELECT
    u.USER_ID,
    u.USERNAME,
    SUM(NVL(d.DISCOUNT,0)) AS TOTAL_DISCOUNTS_GIVEN
FROM users u
LEFT JOIN invoices i ON u.USER_ID = i.USER_ID
LEFT JOIN invoices_details d ON i.INVOICE_ID = d.INVOICE_ID
GROUP BY u.USER_ID, u.USERNAME;


-- Daily Sales Revenue Per Each User
CREATE OR REPLACE VIEW V_USER_DAILY_REVENUE AS
SELECT
    u.USER_ID,
    u.USERNAME,
    TRUNC(i.INVOICE_DATE) AS SALE_DAY,
    SUM(d.QUANTITY * d.UNIT_PRICE - NVL(d.DISCOUNT,0)) AS DAILY_REVENUE
FROM users u
JOIN invoices i ON u.USER_ID = i.USER_ID
JOIN invoices_details d ON i.INVOICE_ID = d.INVOICE_ID
GROUP BY u.USER_ID, u.USERNAME, TRUNC(i.INVOICE_DATE);


-- Total Users
CREATE OR REPLACE VIEW V_KPI_TOTAL_USERS AS
SELECT COUNT(*) AS TOTAL_USERS
FROM users;

-- Total Active Users
CREATE OR REPLACE VIEW V_KPI_ACTIVE_USERS AS
SELECT COUNT(*) AS ACTIVE_USERS
FROM users
WHERE STATUS = 'ACTIVE';

select * from v_kpi_active_users;

-- Total Inactive Users
CREATE OR REPLACE VIEW V_KPI_INACTIVE_USERS AS
SELECT COUNT(*) AS ACTIVE_USERS
FROM users
WHERE STATUS = 'INACTIVE';

SELECT * FROM V_KPI_INACTIVE_USERS;

