
-- Entry Script for Bills_Details Table
INSERT INTO bills_details (bill_id, product_id, quantity, unit_price, discount)
VALUES ((SELECT bill_id FROM bills WHERE bill_id = 1),1,50,(SELECT sales_price FROM products WHERE product_id = 1),0.05);
INSERT INTO bills_details (bill_id, product_id, quantity, unit_price, discount)
VALUES ((SELECT bill_id FROM bills WHERE bill_id = 2), 2, 10, (SELECT sales_price FROM products WHERE product_id = 2), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 3), 3, 15, (SELECT sales_price FROM products WHERE product_id = 3), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 4), 4, 20, (SELECT sales_price FROM products WHERE product_id = 4), 0.00);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 5), 5, 12, (SELECT sales_price FROM products WHERE product_id = 5), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 6), 6, 25, (SELECT sales_price FROM products WHERE product_id = 6), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 7), 7, 18, (SELECT sales_price FROM products WHERE product_id = 7), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 8), 8, 30, (SELECT sales_price FROM products WHERE product_id = 8), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 9), 9, 22, (SELECT sales_price FROM products WHERE product_id = 9), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 10), 10, 40, (SELECT sales_price FROM products WHERE product_id = 10), 0.20);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 11), 11, 16, (SELECT sales_price FROM products WHERE product_id = 11), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 12), 12, 28, (SELECT sales_price FROM products WHERE product_id = 12), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 13), 13, 35, (SELECT sales_price FROM products WHERE product_id = 13), 0.18);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 14), 14, 14, (SELECT sales_price FROM products WHERE product_id = 14), 0.04);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 15), 15, 50, (SELECT sales_price FROM products WHERE product_id = 15), 0.25);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 16), 16, 19, (SELECT sales_price FROM products WHERE product_id = 16), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 17), 17, 33, (SELECT sales_price FROM products WHERE product_id = 17), 0.11);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 18), 18, 21, (SELECT sales_price FROM products WHERE product_id = 18), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 19), 19, 45, (SELECT sales_price FROM products WHERE product_id = 19), 0.22);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 20), 20, 23, (SELECT sales_price FROM products WHERE product_id = 20), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 21), 21, 37, (SELECT sales_price FROM products WHERE product_id = 21), 0.14);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 22), 22, 26, (SELECT sales_price FROM products WHERE product_id = 22), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 23), 23, 32, (SELECT sales_price FROM products WHERE product_id = 23), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 24), 24, 17, (SELECT sales_price FROM products WHERE product_id = 24), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 25), 25, 48, (SELECT sales_price FROM products WHERE product_id = 25), 0.28);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 26), 26, 20, (SELECT sales_price FROM products WHERE product_id = 26), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 27), 27, 29, (SELECT sales_price FROM products WHERE product_id = 27), 0.13);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 28), 28, 11, (SELECT sales_price FROM products WHERE product_id = 28), 0.02);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 29), 29, 36, (SELECT sales_price FROM products WHERE product_id = 29), 0.21);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 30), 30, 24, (SELECT sales_price FROM products WHERE product_id = 30), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 31), 31, 41, (SELECT sales_price FROM products WHERE product_id = 31), 0.26);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 32), 32, 12, (SELECT sales_price FROM products WHERE product_id = 32), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 33), 33, 18, (SELECT sales_price FROM products WHERE product_id = 33), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 34), 34, 25, (SELECT sales_price FROM products WHERE product_id = 34), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 35), 35, 14, (SELECT sales_price FROM products WHERE product_id = 35), 0.04);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 36), 36, 30, (SELECT sales_price FROM products WHERE product_id = 36), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 37), 37, 22, (SELECT sales_price FROM products WHERE product_id = 37), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 38), 38, 40, (SELECT sales_price FROM products WHERE product_id = 38), 0.20);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 39), 39, 16, (SELECT sales_price FROM products WHERE product_id = 39), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 40), 40, 28, (SELECT sales_price FROM products WHERE product_id = 40), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 41), 41, 35, (SELECT sales_price FROM products WHERE product_id = 41), 0.18);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 42), 42, 20, (SELECT sales_price FROM products WHERE product_id = 42), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 43), 43, 45, (SELECT sales_price FROM products WHERE product_id = 43), 0.22);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 44), 44, 24, (SELECT sales_price FROM products WHERE product_id = 44), 0.11);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 45), 45, 50, (SELECT sales_price FROM products WHERE product_id = 45), 0.25);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 46), 46, 19, (SELECT sales_price FROM products WHERE product_id = 46), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 47), 47, 33, (SELECT sales_price FROM products WHERE product_id = 47), 0.14);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 48), 48, 21, (SELECT sales_price FROM products WHERE product_id = 48), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 49), 49, 36, (SELECT sales_price FROM products WHERE product_id = 49), 0.17);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 50), 50, 23, (SELECT sales_price FROM products WHERE product_id = 50), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 51), 51, 41, (SELECT sales_price FROM products WHERE product_id = 51), 0.26);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 52), 52, 26, (SELECT sales_price FROM products WHERE product_id = 52), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 53), 53, 32, (SELECT sales_price FROM products WHERE product_id = 53), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 54), 54, 17, (SELECT sales_price FROM products WHERE product_id = 54), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 55), 55, 48, (SELECT sales_price FROM products WHERE product_id = 55), 0.28);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 56), 56, 20, (SELECT sales_price FROM products WHERE product_id = 56), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 57), 57, 29, (SELECT sales_price FROM products WHERE product_id = 57), 0.13);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 58), 58, 11, (SELECT sales_price FROM products WHERE product_id = 58), 0.02);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 59), 59, 36, (SELECT sales_price FROM products WHERE product_id = 59), 0.21);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 60), 60, 24, (SELECT sales_price FROM products WHERE product_id = 60), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 61), 61, 41, (SELECT sales_price FROM products WHERE product_id = 61), 0.26);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 62), 62, 15, (SELECT sales_price FROM products WHERE product_id = 62), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 63), 63, 22, (SELECT sales_price FROM products WHERE product_id = 63), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 64), 64, 18, (SELECT sales_price FROM products WHERE product_id = 64), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 65), 65, 30, (SELECT sales_price FROM products WHERE product_id = 65), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 66), 66, 25, (SELECT sales_price FROM products WHERE product_id = 66), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 67), 67, 40, (SELECT sales_price FROM products WHERE product_id = 67), 0.20);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 68), 68, 12, (SELECT sales_price FROM products WHERE product_id = 68), 0.04);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 69), 69, 28, (SELECT sales_price FROM products WHERE product_id = 69), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 70), 70, 35, (SELECT sales_price FROM products WHERE product_id = 70), 0.18);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 71), 71, 20, (SELECT sales_price FROM products WHERE product_id = 71), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 72), 72, 45, (SELECT sales_price FROM products WHERE product_id = 72), 0.22);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 73), 73, 16, (SELECT sales_price FROM products WHERE product_id = 73), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 74), 74, 33, (SELECT sales_price FROM products WHERE product_id = 74), 0.14);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 75), 75, 21, (SELECT sales_price FROM products WHERE product_id = 75), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 76), 76, 36, (SELECT sales_price FROM products WHERE product_id = 76), 0.17);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 77), 77, 23, (SELECT sales_price FROM products WHERE product_id = 77), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 78), 78, 41, (SELECT sales_price FROM products WHERE product_id = 78), 0.26);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 79), 79, 26, (SELECT sales_price FROM products WHERE product_id = 79), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 80), 80, 32, (SELECT sales_price FROM products WHERE product_id = 80), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 81), 81, 17, (SELECT sales_price FROM products WHERE product_id = 81), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 82), 82, 48, (SELECT sales_price FROM products WHERE product_id = 82), 0.28);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 83), 83, 20, (SELECT sales_price FROM products WHERE product_id = 83), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 84), 84, 29, (SELECT sales_price FROM products WHERE product_id = 84), 0.13);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 85), 85, 11, (SELECT sales_price FROM products WHERE product_id = 85), 0.02);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 86), 86, 36, (SELECT sales_price FROM products WHERE product_id = 86), 0.21);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 87), 87, 24, (SELECT sales_price FROM products WHERE product_id = 87), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 88), 88, 41, (SELECT sales_price FROM products WHERE product_id = 88), 0.26);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 89), 89, 15, (SELECT sales_price FROM products WHERE product_id = 89), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 90), 90, 38, (SELECT sales_price FROM products WHERE product_id = 90), 0.16);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 91), 91, 20, (SELECT sales_price FROM products WHERE product_id = 91), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 92), 92, 15, (SELECT sales_price FROM products WHERE product_id = 92), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 93), 93, 22, (SELECT sales_price FROM products WHERE product_id = 93), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 94), 94, 18, (SELECT sales_price FROM products WHERE product_id = 94), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 95), 95, 30, (SELECT sales_price FROM products WHERE product_id = 95), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 92), 93, 25, (SELECT sales_price FROM products WHERE product_id = 93), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 93), 94, 20, (SELECT sales_price FROM products WHERE product_id = 94), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 94), 95, 35, (SELECT sales_price FROM products WHERE product_id = 95), 0.18);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 95), 92, 14, (SELECT sales_price FROM products WHERE product_id = 92), 0.04);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 92), 94, 40, (SELECT sales_price FROM products WHERE product_id = 94), 0.20);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 93), 95, 16, (SELECT sales_price FROM products WHERE product_id = 95), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 96), 90, 20, (SELECT sales_price FROM products WHERE product_id = 90), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 97), 85, 15, (SELECT sales_price FROM products WHERE product_id = 85), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 98), 75, 25, (SELECT sales_price FROM products WHERE product_id = 75), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 99), 60, 18, (SELECT sales_price FROM products WHERE product_id = 60), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 100), 70, 30, (SELECT sales_price FROM products WHERE product_id = 70), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 101), 80, 22, (SELECT sales_price FROM products WHERE product_id = 80), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 102), 65, 28, (SELECT sales_price FROM products WHERE product_id = 65), 0.11);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 103), 55, 35, (SELECT sales_price FROM products WHERE product_id = 55), 0.18);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 104), 45, 16, (SELECT sales_price FROM products WHERE product_id = 45), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 105), 25, 40, (SELECT sales_price FROM products WHERE product_id = 25), 0.20);


SELECT * FROM BILLS_DETAILS ORDER BY BILL_ID;
select * from bills order by bill_id;

INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 106), 90, 22, (SELECT sales_price FROM products WHERE product_id = 90), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 107), 85, 18, (SELECT sales_price FROM products WHERE product_id = 85), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 108), 75, 25, (SELECT sales_price FROM products WHERE product_id = 75), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 109), 60, 30, (SELECT sales_price FROM products WHERE product_id = 60), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 110), 70, 20, (SELECT sales_price FROM products WHERE product_id = 70), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 111), 80, 28, (SELECT sales_price FROM products WHERE product_id = 80), 0.11);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 112), 65, 35, (SELECT sales_price FROM products WHERE product_id = 65), 0.18);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 113), 55, 16, (SELECT sales_price FROM products WHERE product_id = 55), 0.05);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 114), 45, 40, (SELECT sales_price FROM products WHERE product_id = 45), 0.20);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 115), 25, 19, (SELECT sales_price FROM products WHERE product_id = 25), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 116), 30, 33, (SELECT sales_price FROM products WHERE product_id = 30), 0.14);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 117), 35, 21, (SELECT sales_price FROM products WHERE product_id = 35), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 118), 40, 36, (SELECT sales_price FROM products WHERE product_id = 40), 0.17);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 119), 50, 23, (SELECT sales_price FROM products WHERE product_id = 50), 0.08);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 120), 52, 41, (SELECT sales_price FROM products WHERE product_id = 52), 0.26);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 121), 58, 26, (SELECT sales_price FROM products WHERE product_id = 58), 0.10);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 122), 62, 32, (SELECT sales_price FROM products WHERE product_id = 62), 0.15);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 123), 64, 17, (SELECT sales_price FROM products WHERE product_id = 64), 0.06);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 124), 68, 48, (SELECT sales_price FROM products WHERE product_id = 68), 0.28);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 125), 72, 20, (SELECT sales_price FROM products WHERE product_id = 72), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 126), 74, 29, (SELECT sales_price FROM products WHERE product_id = 74), 0.13);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 127), 76, 11, (SELECT sales_price FROM products WHERE product_id = 76), 0.02);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 128), 78, 36, (SELECT sales_price FROM products WHERE product_id = 78), 0.21);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 129), 82, 24, (SELECT sales_price FROM products WHERE product_id = 82), 0.12);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 130), 88, 41, (SELECT sales_price FROM products WHERE product_id = 88), 0.26);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 106), 91, 15, (SELECT sales_price FROM products WHERE product_id = 91), 0.07);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 107), 92, 38, (SELECT sales_price FROM products WHERE product_id = 92), 0.16);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 108), 93, 20, (SELECT sales_price FROM products WHERE product_id = 93), 0.09);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 109), 94, 27, (SELECT sales_price FROM products WHERE product_id = 94), 0.11);
INSERT INTO bills_details VALUES ((SELECT bill_id FROM bills WHERE bill_id = 110), 95, 34, (SELECT sales_price FROM products WHERE product_id = 95), 0.19);


select * from cat;
select * from bills;

select * from bills_details;