-- Entry Scripts for all the tables of the database

-- Entry Script for Roles Table
-- Roles (Only 4 roles as per your ENUM)
INSERT ALL
 INTO ROLES (ROLE_ID, ROLENAME, PERMISSIONS) VALUES (1, 'ADMIN', '{"users": ["create","read","update","delete"], "products": ["create","read","update","delete"], "reports": ["read"]}')
 INTO ROLES (ROLE_ID, ROLENAME, PERMISSIONS) VALUES (2, 'MANAGER', '{"products": ["create","read","update"], "inventory": ["read","update"], "reports": ["read"]}')
 INTO ROLES (ROLE_ID, ROLENAME, PERMISSIONS) VALUES (3, 'CASHIER', '{"sales": ["create","read"], "products": ["read"], "customers": ["read"]}')
 INTO ROLES (ROLE_ID, ROLENAME, PERMISSIONS) VALUES (4, 'OTHER', '{"basic": ["read"]}')
SELECT 1 FROM DUAL;

-- Entry Scripts for Customers Table
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'OMAR SULTANI', '0794125523', 'omar.sultani@gmail.com', 'Herat, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'FARID AHMADZAI', '0794125524', 'farid.ahmadzai@gmail.com', 'Kandahar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'LAILA KARIMI', '0794125525', 'laila.karimi@gmail.com', 'Bamyan, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'ZAHRA NOORI', '0794125526', 'zahra.noori@gmail.com', 'Mazar-i-Sharif, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'HAMIDULLAH WARDAK', '0794125527', 'hamid.wardak@gmail.com', 'Wardak, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'MARYAM QADERI', '0794125528', 'maryam.qaderi@gmail.com', 'Parwan, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SAMIULLAH STANIKZAI', '0794125529', 'sami.stanikzai@gmail.com', 'Logar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SHABNAM HAIDARI', '0794125530', 'shabnam.haidari@gmail.com', 'Takhar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'NASIR AHMAD', '0794125531', 'nasir.ahmad@gmail.com', 'Khost, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'FARZANA HAKIMI', '0794125532', 'farzana.hakimi@gmail.com', 'Herat, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'NOORULLAH SAFI', '0794125533', 'noorullah.safi@gmail.com', 'Kandahar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SAHAR AHMADI', '0794125534', 'sahar.ahmadi@gmail.com', 'Balkh, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'BILAL STANIKZAI', '0794125535', 'bilal.stanikzai@gmail.com', 'Logar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'HOMA SADAT', '0794125536', 'homa.sadat@gmail.com', 'Badghis, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'KHALIDULLAH NOORI', '0794125537', 'khalid.noori@gmail.com', 'Kunduz, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'RAZIA QADERI', '0794125538', 'razia.qaderi@gmail.com', 'Bamyan, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'AZIZULLAH KARIMI', '0794125539', 'aziz.karimi@gmail.com', 'Wardak, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'MINA WAHIDI', '0794125540', 'mina.wahidi@gmail.com', 'Takhar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'LATIFULLAH SAFI', '0794125541', 'latif.safi@gmail.com', 'Khost, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SAMIRA HASHIMI', '0794125542', 'samira.hashimi@gmail.com', 'Samangan, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'YASINULLAH KAKAR', '0794125543', 'yasin.kakar@gmail.com', 'Helmand, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'FARZANA SADAT', '0794125544', 'farzana.sadat@gmail.com', 'Nangarhar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'HAROON AZIZI', '0794125545', 'haroon.azizi@gmail.com', 'Kapisa, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'NILOOFAR POPAL', '0794125546', 'niloofar.popal@gmail.com', 'Ghazni, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SHAFIULLAH BARAKZAI', '0794125547', 'shafi.barakzai@gmail.com', 'Zabul, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'LAILA YOUSUFI', '0794125548', 'laila.yousufi@gmail.com', 'Panjshir, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'OMID SHIRZAI', '0794125549', 'omid.shirzai@gmail.com', 'Kabul, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SAHAR HAKIMI', '0794125550', 'sahar.hakimi@gmail.com', 'Herat, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'AHMADULLAH PAKTIAWAL', '0794125551', 'ahmad.paktiawal@gmail.com', 'Paktia, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'ROQIA AHMADI', '0794125552', 'roqia.ahmadi@gmail.com', 'Balkh, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'HAMID STANIKZAI', '0794125553', 'hamid.stanikzai@gmail.com', 'Logar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'PARWANA SADAT', '0794125554', 'parwana.sadat@gmail.com', 'Badghis, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'MAHMOOD NOORI', '0794125555', 'mahmood.noori@gmail.com', 'Kunduz, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'NARGIS QADERI', '0794125556', 'nargis.qaderi@gmail.com', 'Bamyan, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'QASIM KARIMI', '0794125557', 'qasim.karimi@gmail.com', 'Wardak, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'HASEENA WAHIDI', '0794125558', 'haseena.wahidi@gmail.com', 'Takhar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'RAHIM SAFI', '0794125559', 'rahim.safi@gmail.com', 'Khost, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SORAYA HASHIMI', '0794125560', 'soraya.hashimi@gmail.com', 'Samangan, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'FARID KAKAR', '0794125561', 'farid.kakar@gmail.com', 'Helmand, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'NAJIBA WAHIDI', '0794125572', 'najiba.wahidi@gmail.com', 'Nangarhar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'ZUBAIR AHMADZAI', '0794125573', 'zubair.ahmadzai@gmail.com', 'Kabul, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'MALALAI KARIMI', '0794125574', 'malalai.karimi@gmail.com', 'Herat, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SHAHIDULLAH WARDAK', '0794125575', 'shahid.wardak@gmail.com', 'Wardak, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'FARZANA NOORI', '0794125576', 'farzana.noori@gmail.com', 'Balkh, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'KHALILULLAH SAFI', '0794125577', 'khalil.safi@gmail.com', 'Kandahar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'HORIA SADAT', '0794125578', 'horia.sadat@gmail.com', 'Takhar, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'ABDUL RAHMAN', '0794125579', 'abdul.rahman@gmail.com', 'Khost, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'SHUKRIA HAKIMI', '0794125580', 'shukria.hakimi@gmail.com', 'Samangan, Afghanistan', SYSDATE);
INSERT INTO CUSTOMERS VALUES(CUSTOMER_ID_CUSTOMER_TABLE.nextval, 'JAWADULLAH AZIZI', '0794125581', 'jawad.azizi@gmail.com', 'Kapisa, Afghanistan', SYSDATE);

-- Entry Script for Suppliers Table
select * from suppliers;
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Bismellah Khosti', '0744522556', 'bismellah.khosti@gmail.com', 'Laghman, Afghanistan', sysdate);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Bismellah Khosti', '0744522556', 'bismellah.khosti@gmail.com', 'Laghman, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Rahimullah Safi', '0744522557', 'rahim.safi@gmail.com', 'Kabul, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Farzana Hakimi', '0744522558', 'farzana.hakimi@gmail.com', 'Herat, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Omid Shirzai', '0744522559', 'omid.shirzai@gmail.com', 'Kandahar, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Maryam Qaderi', '0744522560', 'maryam.qaderi@gmail.com', 'Bamyan, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Latifullah Stanikzai', '0744522561', 'latif.stanikzai@gmail.com', 'Logar, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Soraya Wahidi', '0744522562', 'soraya.wahidi@gmail.com', 'Takhar, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Hamidullah Wardak', '0744522563', 'hamid.wardak@gmail.com', 'Wardak, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Zahra Noori', '0744522564', 'zahra.noori@gmail.com', 'Mazar-i-Sharif, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Mahmood Azizi', '0744522565', 'mahmood.azizi@gmail.com', 'Parwan, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Samira Hashimi', '0744522566', 'samira.hashimi@gmail.com', 'Kapisa, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Bilal Stanikzai', '0744522567', 'bilal.stanikzai@gmail.com', 'Ghazni, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Haseena Yousufi', '0744522568', 'haseena.yousufi@gmail.com', 'Zabul, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Khalidullah Noori', '0744522569', 'khalid.noori@gmail.com', 'Panjshir, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Razia Qaderi', '0744522570', 'razia.qaderi@gmail.com', 'Khost, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Azizullah Karimi', '0744522571', 'aziz.karimi@gmail.com', 'Samangan, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Mina Wahidi', '0744522572', 'mina.wahidi@gmail.com', 'Helmand, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Latifa Sadat', '0744522573', 'latifa.sadat@gmail.com', 'Nangarhar, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Jawadullah Azizi', '0744522574', 'jawad.azizi@gmail.com', 'Kapisa, Afghanistan', SYSDATE);
INSERT INTO SUPPLIERS VALUES (SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL, 'Shukria Hakimi', '0744522575', 'shukria.hakimi@gmail.com', 'Farah, Afghanistan', SYSDATE);

-- Entry Script for Categories Table
SELECT * FROM CATEGORIES;
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Energy Drinks', 'All Energy Drinks in this Category', 'mL', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Tissue Papers', 'All Iranian and Pakistan Tissues in this Category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Soft Drinks', 'All carbonated soft drinks in this category', 'mL', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Bottled Water', 'All bottled mineral and spring water in this category', 'Liters', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Cooking Oil', 'All vegetable and olive oils in this category', 'Liters', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Rice', 'All types of rice in this category', 'Kg', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Sugar', 'All types of sugar in this category', 'Kg', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Tea', 'All green and black teas in this category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Coffee', 'All instant and ground coffee in this category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Biscuits', 'All sweet and salty biscuits in this category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Chocolates', 'All chocolates and candies in this category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Milk Powder', 'All powdered milk products in this category', 'Kg', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Fresh Milk', 'All fresh dairy milk in this category', 'Liters', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Yogurt', 'All yogurt products in this category', 'Kg', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Cheese', 'All cheese products in this category', 'Kg', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Detergents', 'All washing powders and detergents in this category', 'Kg', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Shampoos', 'All hair care shampoos in this category', 'mL', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Soaps', 'All bathing and washing soaps in this category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Toothpaste', 'All toothpaste brands in this category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Snacks', 'All chips and salty snacks in this category', 'Packs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Juices', 'All fruit juices in this category', 'Liters', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Spices', 'All cooking spices in this category', 'Kg', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Eggs', 'All types of eggs in this category', 'Dozens', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Bread', 'All bakery breads in this category', 'Loaves', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Ice Cream', 'All ice cream products in this category', 'Scoops', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Cigarettes', 'All cigarette brands in this category', 'Cartons', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Matches', 'All matchboxes in this category', 'Boxes', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Batteries', 'All battery types in this category', 'Pieces', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Light Bulbs', 'All light bulbs in this category', 'Units', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Shoes', 'All footwear in this category', 'Pairs', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Notebooks', 'All school notebooks in this category', 'Sheets', SYSDATE);
INSERT INTO CATEGORIES VALUES (CATEGORY_ID_CATEGORY_TABLE.nextval, 'Perfumes', 'All perfume products in this category', 'Bottles', SYSDATE);

-- Entry Scripts for Products Table
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Bleu De Chanel', 23, '14000.99', 1, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Coca Cola 500mL', 3, '50.00', 1, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pepsi 1L', 3, '90.00', 1, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Nestle Mineral Water 1.5L', 3, '40.00', 2, 300, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Zarghoon Cooking Oil 5L', 5, '750.00', 3, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Indian Basmati Rice 10Kg', 6, '1200.00', 4, 60, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'White Crystal Sugar 5Kg', 7, '500.00', 5, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Green Tea Pack 200g', 8, '250.00', 6, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Nescafe Classic 100g', 9, '450.00', 7, 90, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Oreo Biscuits 12 Pack', 10, '300.00', 8, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Cadbury Dairy Milk 100g', 11, '150.00', 9, 250, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Nido Milk Powder 1Kg', 12, '800.00', 10, 70, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Fresh Cow Milk 1L', 13, '100.00', 11, 300, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Natural Yogurt 500g', 14, '120.00', 12, 180, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Cheddar Cheese 250g', 15, '350.00', 13, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Ariel Detergent 2Kg', 16, '600.00', 14, 90, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Head & Shoulders Shampoo 400mL', 17, '450.00', 15, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Lux Soap 6 Pack', 18, '200.00', 16, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Colgate Toothpaste 150g', 19, '180.00', 17, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Lays Chips 100g', 20, '100.00', 18, 250, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Tropicana Orange Juice 1L', 21, '220.00', 19, 180, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Farm Fresh Eggs', 34, '120.00', 1, 50, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Organic Brown Eggs', 34, '150.00', 1, 40, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Duck Eggs', 34, '180.00', 1, 30, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Quail Eggs', 34, '200.00', 1, 25, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Omega-3 Enriched Eggs', 34, '220.00', 1, 20, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'White Bread Loaf', 33, '80.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Whole Wheat Bread', 33, '100.00', 1, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Afghan Naan', 33, '20.00', 1, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'French Baguette', 33, '120.00', 1, 60, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Multigrain Bread', 33, '150.00', 1, 40, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Vanilla Ice Cream Scoop', 31, '50.00', 1, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Chocolate Ice Cream Tub', 31, '250.00', 1, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Strawberry Ice Cream Cone', 31, '70.00', 1, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Mango Ice Cream Cup', 31, '90.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pistachio Ice Cream Family Pack', 31, '400.00', 1, 50, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Marlboro Red Carton', 30, '2500.00', 1, 30, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pine Blue Pack', 30, '200.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Winston Classic Carton', 30, '2200.00', 1, 25, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Kent Silver Pack', 30, '180.00', 1, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Camel Yellow Carton', 30, '2300.00', 1, 20, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Iranian Matchbox', 28, '20.00', 1, 300, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pakistani Matchbox', 28, '15.00', 1, 400, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Safety Matches Pack', 28, '25.00', 1, 250, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Long Stick Matches', 28, '40.00', 1, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Waterproof Matches', 28, '60.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'A4 Ruled Notebook', 24, '120.00', 1, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Spiral Notebook 200 Pages', 24, '150.00', 1, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Graph Notebook', 24, '180.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pocket Notebook', 24, '90.00', 1, 250, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Hardcover Notebook', 24, '220.00', 1, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Orange Juice 1L', 21, '200.00', 1, 180, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Apple Juice 1L', 21, '190.00', 1, 160, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Mango Juice 500mL', 21, '120.00', 1, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pomegranate Juice 1L', 21, '250.00', 1, 140, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Mixed Fruit Juice 1L', 21, '230.00', 1, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Black Pepper Powder 100g', 22, '150.00', 1, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Turmeric Powder 200g', 22, '180.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Cumin Seeds 250g', 22, '200.00', 1, 90, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Cinnamon Sticks 100g', 22, '220.00', 1, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Cardamom Pods 50g', 22, '300.00', 1, 70, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Leather Formal Shoes', 25, '2500.00', 1, 40, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Sports Running Shoes', 25, '3200.00', 1, 60, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Casual Sneakers', 25, '2800.00', 1, 70, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Sandals Pair', 25, '1500.00', 1, 90, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Winter Boots', 25, '4000.00', 1, 30, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Red Bull 250mL', 1, '150.00', 1, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Monster Energy 500mL', 1, '220.00', 1, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Burn Energy Drink 330mL', 1, '180.00', 1, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Sting Energy 250mL', 1, '100.00', 1, 250, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Power Horse 500mL', 1, '200.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'NOS Energy Drink 473mL', 1, '210.00', 1, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Rockstar Energy 500mL', 1, '230.00', 1, 90, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Full Throttle 473mL', 1, '190.00', 1, 70, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Amp Energy 473mL', 1, '175.00', 1, 60, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Warrior Energy 250mL', 1, '120.00', 1, 110, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Fine Tissue Pack 200 Sheets', 2, '150.00', 1, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Rose Tissue Box 150 Sheets', 2, '130.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pakistani Soft Tissue Pack', 2, '140.00', 1, 90, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Iranian Deluxe Tissue Box', 2, '160.00', 1, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Kleenex Facial Tissue 100 Sheets', 2, '120.00', 1, 150, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Papco Tissue Roll', 2, '110.00', 1, 200, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Soft Touch Tissue Pack 250 Sheets', 2, '170.00', 1, 70, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Royal Tissue Box 200 Sheets', 2, '155.00', 1, 95, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Deluxe Napkin Tissue Pack', 2, '180.00', 1, 60, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Family Pack Tissue Roll', 2, '200.00', 1, 50, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Pantene Pro-V Shampoo 400mL', 17, '420.00', 1, 120, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Sunsilk Black Shine Shampoo 350mL', 17, '380.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Clear Anti-Dandruff Shampoo 500mL', 17, '450.00', 1, 90, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Dove Intense Repair Shampoo 400mL', 17, '460.00', 1, 110, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Herbal Essences Argan Oil Shampoo 300mL', 17, '500.00', 1, 80, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Tresemme Keratin Smooth Shampoo 600mL', 17, '650.00', 1, 70, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Palmolive Naturals Shampoo 350mL', 17, '360.00', 1, 100, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Head & Shoulders Classic Clean 400mL', 17, '480.00', 1, 95, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'Garnier Fructis Strengthening Shampoo 300mL', 17, '440.00', 1, 85, TRUE, SYSDATE);
INSERT INTO PRODUCTS VALUES (PRODUCT_ID_PRODUCTS_TABLE.nextval, 'L’Oreal Elvive Color Protect Shampoo 500mL', 17, '700.00', 1, 60, TRUE, SYSDATE);







