-- STEP 1: CREATING SEQUENCES FOR ALL THE TABLE 
-- CUSTOMER TABLE SEQUENCE
CREATE SEQUENCE CUSTOMER_ID_CUSTOMER_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50000
NOCACHE
NOCYCLE;


CREATE SEQUENCE SUPPLIER_ID_SUPPLIER_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50000
NOCACHE
NOCYCLE;
-- CATEGORY TABLE SEQUENCE
CREATE SEQUENCE CATEGORY_ID_CATEGORY_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50000
NOCACHE
NOCYCLE;

-- PRODUCTS TABLE SEQUENCE
CREATE SEQUENCE PRODUCT_ID_PRODUCTS_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50000
NOCACHE
NOCYCLE;

-- ROLES TABLE SEQUENCE
CREATE SEQUENCE ROLE_ID_ROLES_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50
NOCACHE
NOCYCLE;

-- USERS TABLE SEQUENCE
CREATE SEQUENCE USER_ID_USERS_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 10
NOCACHE
NOCYCLE;
-- BILLS TABLE SEQUENCE
CREATE SEQUENCE BILL_ID_BILLS_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 150000 -- FOR EX: IF THE SYSTEM HANDLES 50000 SUPPLIERS THEN IT MUST PROVIDE AT LEAST 150000 BILLS WITH UNIQUE IDS (EVEN NOT ENOUGH) - (JUST FOR TESTING PURPOSE)
NOCACHE
NOCYCLE;

-- INVOICE TABLE SEQUENCE
CREATE SEQUENCE INVOICE_ID_INVOICE_TABLE
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 150000 -- FOR EX: IF THE SYSTEM HANDLES 50000 CUSTOMERS THEN IT MUST PROVIDE AT LEAST 150000 BILLS WITH UNIQUE IDS (EVEN NOT ENOUGH) - (JUST FOR TESTING PURPOSE)
NOCACHE
NOCYCLE;


-- STEP 2: CREATING TABLES

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT DEFAULT CUSTOMER_ID_CUSTOMER_TABLE.NEXTVAL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_PHONE VARCHAR(15) UNIQUE,
    CUSTOMER_EMAIL VARCHAR(100),
    CUSTOMER_ADDRESS VARCHAR(100),
    CREATED_DATE DATE
);


CREATE TABLE SUPPLIERS(
    SUPPLIER_ID INT DEFAULT SUPPLIER_ID_SUPPLIER_TABLE.NEXTVAL PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(100) NOT NULL,
    SUPPLIER_PHONE VARCHAR(15) UNIQUE NOT NULL,
    SUPPLIER_EMAIL VARCHAR(100) UNIQUE,
    SUPPLIER_ADDRESS VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE CATEGORIES(
    CATEGORY_ID INT DEFAULT CATEGORY_ID_CATEGORY_TABLE.NEXTVAL PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    UNIT_OF_MEASURE CHAR(8) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE PRODUCTS(
    PRODUCT_ID INT DEFAULT PRODUCT_ID_PRODUCTS_TABLE.NEXTVAL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    CATEGORY_ID INT REFERENCES CATEGORIES(CATEGORY_ID),
    SALES_PRICE DECIMAL(10,2) NOT NULL CHECK(SALES_PRICE >= 0),
    SUPPLIER_ID INT REFERENCES SUPPLIERS(SUPPLIER_ID),
    CURRENT_STOCK INT NOT NULL CHECK(CURRENT_STOCK >= 0),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ROLES(
    ROLE_ID INT DEFAULT ROLE_ID_ROLES_TABLE.NEXTVAL PRIMARY KEY,
    ROLENAME VARCHAR(10) DEFAULT 'OTHER' CHECK(ROLENAME IN('ADMIN', 'CASHIER', 'MANAGER', 'OTHER')) NOT NULL,
    PERMISSIONS JSON,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE USERS(
    USER_ID INT DEFAULT USER_ID_USERS_TABLE.NEXTVAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE_ID INT REFERENCES ROLES(ROLE_ID),
    STATUS VARCHAR(10) DEFAULT 'INACTIVE' CHECK(STATUS IN('ACTIVE', 'INACTIVE')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
DROP TABLE USERS;
DROP TABLE ROLES;
SELECT * FROM ROLES;
DESCRIBE USERS;
DESCRIBE ROLES;
CREATE TABLE BILLS(
    BILL_ID INT DEFAULT BILL_ID_BILLS_TABLE.NEXTVAL PRIMARY KEY,
    SUPPLIER_ID INT REFERENCES SUPPLIERS(SUPPLIER_ID),
    USER_ID INT REFERENCES USERS(USER_ID),
    BILL_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL CHECK(AMOUNT >= 0),
    STATUS VARCHAR(10) DEFAULT 'unpaid' CHECK(STATUS IN ('paid', 'unpaid', 'cancel'))
);

CREATE TABLE BILLS_DETAILS(
    BILL_ID INT REFERENCES BILLS(BILL_ID),
    PRODUCT_ID INT REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY INT NOT NULL CHECK(QUANTITY >= 0),
    UNIT_PRICE DECIMAL(10,2) NOT NULL CHECK(UNIT_PRICE >= 0),
    DISCOUNT DECIMAL(5,2) CHECK(DISCOUNT >= 0 AND DISCOUNT <= 100)
);

CREATE TABLE INVOICES(
    INVOICE_ID INT DEFAULT INVOICE_ID_INVOICE_TABLE.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID INT REFERENCES CUSTOMERS(CUSTOMER_ID),
    USER_ID INT REFERENCES USERS(USER_ID),
    INVOICE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS VARCHAR(10) DEFAULT 'unpaid' CHECK(STATUS IN ('paid', 'unpaid', 'cancel')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE INVOICE_DETAILS(
    INVOICE_ID INT REFERENCES INVOICES(INVOICE_ID),
    PRODUCT_ID INT REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY INT NOT NULL CHECK(QUANTITY >= 0),
    UNIT_PRICE DECIMAL(10,2) NOT NULL CHECK(UNIT_PRICE >= 0),
    DISCOUNT DECIMAL(5,2) CHECK(DISCOUNT >=0 AND DISCOUNT <= 100)
);


-- THESE ARE ALL THE TABLES WE HAVE!
SELECT * FROM SUPPLIERS;
SELECT * FROM CUSTOMERS;
SELECT * FROM CATEGORIES;
SELECT * FROM PRODUCTS;
SELECT * FROM USERS;
SELECT * FROM BILLS;
SELECT * FROM INVOICES;
SELECT * FROM ROLES;


SELECT * FROM INVOICE_DETAILS;
SELECT * FROM BILL_DETAILS;
SELECT * FROM CAT;































-- ADDITIONAL WORK DONE
RENAME CUSTOMER_ID_CUST_TABLE TO CUSTOMER_ID_CUSTOMER_TABLE;



ALTER TABLE CATEGORIES
MODIFY(DESCRIPTION VARCHAR(255));

