-- Users and their Roles
-- First: Creating two users:

CREATE USER C##GROCERY_MANAGER IDENTIFIED BY manager123;
GRANT CREATE SESSION TO C##GROCERY_MANAGER;

CREATE USER C##GROCERY_CASHIER IDENTIFIED BY cashier123;
GRANT CREATE SESSION TO C##GROCERY_CASHIER;

-- Second: Creating two roles
CREATE ROLE GROCERY_MANAGER_ROLE;
CREATE ROLE GROCERY_CASHIER_ROLE;


-- Third: Assigning roles to the users
GRANT GROCERY_MANAGER_ROLE TO C##GROCERY_MANAGER;
GRANT GROCERY_CASHIER_ROLE TO C##GROCERY_CASHIER;


-- Fourth: Granting Schema Level Permissions to these roles (for Managers in this Step)
-- Allowing manager full access to all main tables
GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.PRODUCTS TO GROCERY_MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.CATEGORIES TO GROCERY_MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.SUPPLIERS TO GROCERY_MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.CUSTOMERS TO GROCERY_MANAGER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.BILLS TO GROCERY_MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.BILLS_DETAILS TO GROCERY_MANAGER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.INVOICES TO GROCERY_MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##GROCERY_ADMIN.INVOICES_DETAILS TO GROCERY_MANAGER_ROLE;

-- View users/roles
GRANT SELECT ON C##GROCERY_ADMIN.USERS TO GROCERY_MANAGER_ROLE;
GRANT SELECT ON C##GROCERY_ADMIN.ROLES TO GROCERY_MANAGER_ROLE;






-- Fifth: Granting Schema Level Permissions to these roles (for Cashiers in this Step)
-- Cashier can read all master data
GRANT SELECT ON C##GROCERY_ADMIN.PRODUCTS TO GROCERY_CASHIER_ROLE;
GRANT SELECT ON C##GROCERY_ADMIN.CATEGORIES TO GROCERY_CASHIER_ROLE;
GRANT SELECT ON C##GROCERY_ADMIN.SUPPLIERS TO GROCERY_CASHIER_ROLE;
GRANT SELECT ON C##GROCERY_ADMIN.CUSTOMERS TO GROCERY_CASHIER_ROLE;

-- Cashier can READ bills but NOT change them
GRANT SELECT ON C##GROCERY_ADMIN.BILLS TO GROCERY_CASHIER_ROLE;
GRANT SELECT ON C##GROCERY_ADMIN.BILLS_DETAILS TO GROCERY_CASHIER_ROLE;

-- Cashier can create invoices for customers
GRANT SELECT, INSERT, UPDATE, DELETE 
ON C##GROCERY_ADMIN.INVOICES TO GROCERY_CASHIER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE 
ON C##GROCERY_ADMIN.INVOICES_DETAILS TO GROCERY_CASHIER_ROLE;
